/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "CustomLookAndFeel.h"

//==============================================================================
/**
*/
class StereoChorusAudioProcessorEditor  : public AudioProcessorEditor,
                                          public SliderListener,
                                          public Timer
{
public:
    StereoChorusAudioProcessorEditor (StereoChorusAudioProcessor* ownerFilter);
    ~StereoChorusAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
    void sliderValueChanged(Slider* slider);
    void timerCallback();
    
    CustomLookAndFeel lookAndFeel;
    
private:
    Slider delaySlider, feedbackSlider, modSlider, mixSlider;
    
    StereoChorusAudioProcessor* getProcessor() const
    {
        return static_cast<StereoChorusAudioProcessor*> (getAudioProcessor());
    }
    
};


#endif  // PLUGINEDITOR_H_INCLUDED
